name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          echo "${{ github.repository }}"
